cinema/cinema/Controllers/ArrangementController.cs
using cinema.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace cinema.Controllers;

public class ArrangementController : Controller
{
    private readonly IArrangementRepository _arrangementRepository;

    public ArrangementController(IArrangementRepository arrangementRepository)
    {
        _arrangementRepository = arrangementRepository;
    }

    [HttpGet]
    [Authorize(Policy = "Manager")]
    [Route("/arrangements")]
    public IActionResult Arrangements([FromQuery] string arrangement,[FromQuery] int price)
    {
        if (!string.IsNullOrEmpty(arrangement))
        {
            ViewBag.SuccessMessage = "De prijs van " + arrangement + " arrangement is nu " +price + " euro";
        }
        ViewBag.arrangements = _arrangementRepository.FindAllArrangements();
        return View();
    }


    [HttpPost]
    [Authorize(Policy = "Manager")]
    [Route("/arrangement-aanpassen")]
    public IActionResult Edit([FromForm] int price, [FromForm] int id)
    {
        var arrangement = _arrangementRepository.FindById(id);
        arrangement.Price = price;
        _arrangementRepository.save();

        return RedirectToAction(nameof(Arrangements), new {arrangement = arrangement.Name,price = arrangement.Price});
    }
}

cinema/cinema/Controllers/ShowsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;
using cinema.Services;
using cinema.Filters;
using cinema.Repositories;

namespace cinema.Controllers
{
    public class ShowsController : Controller
    {
        private readonly IShowRepository _showRepository;
        private readonly IShowService _showService;

        public ShowsController(IShowRepository showRepository, IShowService service)
        {
            
            _showRepository = showRepository;
            _showService = service;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {

            var showList = _showRepository.ListOfShowsPerDate();
            var showPerMoviePerDateDict = _showService.GetShowsPerMoviePerDay(showList);

            ShowsFilter filter = new ShowsFilter(showList);
            ViewData["ShowsFilter"] = filter;

            return View(showPerMoviePerDateDict);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _showRepository.FindShowById(id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (ModelState.IsValid)
            {
                _showRepository.Add(show);
                _showRepository.SaveShow();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var show = await _showRepository.FindShowByIdWithoutFirstOrDefault(id);
            if (show == null)
            {
                return NotFound();
            }
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _showRepository.UpdateShow(show);
                    _showRepository.SaveShow();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var show = await _showRepository.FindShowById(id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _showRepository.FindShowByIdWithoutFirstOrDefault(id);
            _showRepository.RemoveShow(show);
            _showRepository.SaveShow();
            return RedirectToAction(nameof(Index));
        }

        public bool ShowExists(int id)
        {
            return _showRepository.ShowExists(id);
        }

        //GET: Shows/Daily
        public IActionResult Daily()
        {
            return View(_showRepository.SortedListOfShowsThatStartToday());
        }

        [HttpGet, HttpPost, ActionName("Filter")]
        public IActionResult Filter()
        {
            List<Show> shows = _showRepository.ListOfMoviesThatStartSoon();
            ShowsFilter filter = new ShowsFilter(shows);      
            if(Request.Method == HttpMethod.Post.Method)
            {
                if(Request.Form["search"] != "")
                    filter.input = Request.Form["search"];
                if (Request.Form["len"] != "")
                    filter.maxlength = Convert.ToDouble(Request.Form["len"]);
                if (Request.Form["date"] != "")
                    filter.date = Convert.ToDateTime(Request.Form["date"]);
                if (Request.Form["threed"] != "")
                    if (Request.Form["threed"] == "on")
                        filter.threed = true;
                    else
                        filter.threed = false;
                foreach (string language in filter.languages.Keys)
                    if (Request.Form[language] == "on")
                        filter.languages[language] = true;
                    else
                        filter.languages[language] = false;
                foreach (string genre in filter.genres.Keys)
                    if (Request.Form[genre] == "on")
                        filter.genres[genre] = true;
                    else
                        filter.genres[genre] = false;
                foreach (string kijkwijzer in filter.kijkwijzers.Keys)
                    if (Request.Form[kijkwijzer] == "on")
                        filter.kijkwijzers[kijkwijzer] = true;
                    else
                        filter.kijkwijzers[kijkwijzer] = false;
            }
            shows = filter.Apply(shows);
            ViewData["ShowsFilter"] = filter;
            return View("Index", _showService.GetShowsPerMoviePerDay(shows));
        }
    }
}

cinema/cinema/Controllers/SubscribersController.cs
using cinema.Data;
using cinema.Models;
using cinema.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace cinema.Controllers;

public class SubscribersController : Controller
{
    private readonly ISubscriberRepository _subscriberRepository;

    public SubscribersController(ISubscriberRepository subscriberRepository)
    {
        _subscriberRepository = subscriberRepository;
    }

    [HttpGet]
    [Route("/subscriber")]
    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    [Route("/subscriber/create")]
    public IActionResult Create(
        [FromForm] string email)
    {
        Subscriber subscriber = new Subscriber();
        subscriber.Email = email;
        
        _subscriberRepository.addSubscriber(subscriber);
        _subscriberRepository.saveSubscriber();
        return View(subscriber);
    }
}

cinema/cinema/Controllers/VoucherController.cs
using cinema.Data;
using cinema.Models;
using cinema.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IronBarCode;

namespace cinema.Controllers;

public class VoucherController : Controller
{
    private readonly IVoucherRepository _voucherRepository;

    private readonly IUserRepositroy _userRepository;
    
    public VoucherController(IVoucherRepository voucherRepository, IUserRepositroy userRepository)
    {
        _voucherRepository = voucherRepository;
        _userRepository = userRepository;
    }

    [HttpGet]
    [Authorize(Roles="Beheerder,Manager,Kassamedewerker,Back office Manager")]
    [Route("/bioscoop-bonnen")]
    public IActionResult Index([FromQuery] string arrangement,[FromQuery] int price)
    {
        ViewBag.VoucherTypes = _voucherRepository.FindAllVoucherTypes();
        return View();
    }
    
    [HttpGet]
    [Authorize(Roles="Beheerder,Manager,Kassamedewerker,Back office Manager")]
    [Route("/Voucher/Create")]
    public IActionResult Create([FromQuery] int id)
    {
        ViewBag.VoucherType = _voucherRepository.FindById(id);
        return View();
    }

    [HttpGet]
    [Authorize(Roles="Beheerder,Manager,Kassamedewerker,Back office Manager")]
    [Route("/Voucher/Overview")]
    public IActionResult Overview([FromQuery] int voucherId, [FromQuery] int quantity)
    {
        VoucherType voucherType = _voucherRepository.FindById(voucherId);
        ViewBag.Quantity = quantity;
        ViewBag.TotalPrice = voucherType.price * quantity;
        ViewBag.VoucherType = voucherType;
        return View();
    }
    
    [HttpPost]
    [Authorize(Roles="Beheerder,Manager,Kassamedewerker,Back office Manager")]
    public RedirectToActionResult Buy([FromForm] int voucherTypeId, [FromForm] int quantity,[FromForm] string user)
    {
        VoucherType voucherType = _voucherRepository.FindById(voucherTypeId);
        ViewBag.Quantity = quantity;
        ViewBag.TotalPrice = voucherType.price * quantity;
        ViewBag.VoucherType = _voucherRepository.FindById(voucherTypeId);
        Random rnd = new Random();

        var currentUser = _userRepository.FindByUsername(user);
        var code = rnd.Next(1, 100000);

        if (voucherType.name == "1 bioscoopbon")
        {
            GeneratedBarcode barcode = IronBarCode.BarcodeWriter.CreateBarcode(code.ToString() + voucherType.Id.ToString() , BarcodeEncoding.QRCode);
            ViewBag.barcode = barcode.SaveAsImage(Directory.GetCurrentDirectory() + "\\wwwroot\\images\\" + voucherType.Id + code +".png");
        }else if(voucherType.name == "MaDiWoDo")
        {
            for (int i = 0; i < 4; i++)
            {
                GeneratedBarcode barcode = IronBarCode.BarcodeWriter.CreateBarcode(code.ToString() + voucherType.Id.ToString() + i.ToString() , BarcodeEncoding.QRCode);
                ViewBag.barcode = barcode.SaveAsImage(Directory.GetCurrentDirectory() + "\\wwwroot\\images\\" + voucherType.Id + code + i + ".png");
            }
        }else if (voucherType.name == "10 rittenkaart")
        {
            for (int i = 0; i < 10; i++)
            {
                GeneratedBarcode barcode = IronBarCode.BarcodeWriter.CreateBarcode(code.ToString() + voucherType.Id.ToString() + i.ToString() , BarcodeEncoding.QRCode);
                ViewBag.barcode = barcode.SaveAsImage(Directory.GetCurrentDirectory() + "\\wwwroot\\images\\" + voucherType.Id + code + i + ".png");
            }
        }
        
        for (int i = 0; i < quantity; i++)
        {
            _voucherRepository.AddNewVoucher(
                new Voucher()
                {
                    VoucherType = voucherType,
                    user = currentUser,
                    code = code
                }
                );
        }

        _voucherRepository.save();
       
        return RedirectToAction(nameof(Result), new {message = "Bedankt, het kopen van het kaartje is gelukt"});

    }
    
    
    [HttpGet]
    [Authorize(Roles="Beheerder,Manager,Kassamedewerker,Back office Manager")]
    [Route("/vouchers")]
    public IActionResult Result()
    {
        var currentUser = _userRepository.FindByName(User.Identity.Name);

        ViewBag.Vouchers = _voucherRepository.findByUser(currentUser);
        return View();
    }

}

cinema/cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
@inject SignInManager<CinemaIdentityUser> SignInManager
@inject UserManager<CinemaIdentityUser> UserManager


<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand logo" href="#">
                <img src="~/imagesStyling/logo-se.png" alt="logo" class="img-responsive"/>
            </a>
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cinema</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Shows" asp-action="Index">Voorstellingen</a>
                    </li>
                    @if (User.IsInRole("Manager"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Arrangement" asp-action="Arrangements">Arrangementen</a>
                        </li>
                    }
                    @if (User.IsInRole("Manager") || User.IsInRole("Kassamedewerker") || User.IsInRole("Manager") || User.IsInRole("Beheerder") || User.IsInRole("Back office Manager"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Voucher" asp-action="index">Tegoedbonnen</a>
                        </li>
                    }
                </ul>

                <partial name="_LoginPartial"/>

            </div>
        </div>
    </nav>
</header>
<div class="container my-5 py-5">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<div class="footer-containe mt-5 pt-5">
    <div id="mapssubscribe" class="container-fluid mt-5 pt-5">
        <div class="row justify-content-evenly align-items-start">
            <div class="col-4">
                <input type="text" id="txtSource" placeholder="Vanaf"/>
                <input type="button" value="Route" onclick="GetRoute()" class="btn btn-primary btn-lg"/>

                <div id="Dropdown">
                    <b>Ik kom: </b>
                    <select id="mode">
                        <option value="DRIVING">Met de auto</option>
                        <option value="WALKING">Lopend</option>
                        <option value="BICYCLING">Fietsend</option>
                        <option value="TRANSIT">Met de OV</option>
                    </select>
                </div>
                <hr/>
                <div id="dvDistance" style="font-weight:bold; text-align: center">
                </div>
                <div id="dvMap">
                </div>
                <div id="dvPanel">
                </div>
            </div>
            <div class="col-4">
                <div>
                    <h4>Aanmelden voor nieuwsbrief</h4>
                    <form method="post" asp-action="Create" asp-controller="Subscribers">
                        <input name="email" type="text" placeholder="Email adres">
                        <input type="submit" class="btn btn-primary btn-lg" value="Aanmelden">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="shadow footer text-muted bg-black py-4 fixed-bottom">
    <div class="container footer-container text-white d-flex justify-content-between">
        <div>
            &copy; 2022 - cinema - <a asp-page="/Privacy" class="text-decoration-none">privacy</a>
        </div>
        <div>
            <a class="social-media text-decoration-none" href="https://www.facebook.com/avans/">
                <img src="~/imagesStyling/fb-bw.png" alt="fb" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
            <a class="social-media text-decoration-none" href="https://www.instagram.com/avanshogeschool/?hl=en">
                <img src="~/imagesStyling/ig-bw.png" alt="ig" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
            <a class="social-media text-decoration-none" href="https://twitter.com/avanshogeschool?lang=en">
                <img src="~/imagesStyling/tw-bw.png" alt="tw" class="img-responsive mx-2" style="max-width: 30px"/>
            </a>
        </div>

    </div>
</footer>

<script src="~/lib/bootstrap/bootstrap.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXagAu3PsqAZ2hW-1CA7HnMY0BjBF87GM&libraries=places">  
              </script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>